config/routes.rb
Rails.application.routes.draw do

  root controller: :landing, action: :index
  resources :articles, only: [:new, :create] do
    resources :comments, only: [:create, :new]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  has_many :comments
  validates :title, presence: true
  validates :content, presence: true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :article
  validates :body, presence: true
  validates_format_of :email, with: /\A\w[a-zA-Z0-9_.-]*\@[a-z]+\.[a-z]+\Z/i, if: :email?
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

  def new
    @article = Article.new
  end

  def create
    @article = Article.new(article_params)
    @comment = Comment.new(article: @article)
    @article.save ? article_created : (render :new)

  end

  def show
    @article = Article.find(params[:id])
  end

  private

  def article_params
    params[:article].permit(:title, :content)
  end

  def article_created
    flash[:notice] = "Article was successfully created."
    redirect_to root_path
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def new
    @article = Article.find(params[:article_id])
    @comment = Comment.new(article: @article)
  end

  def create
    @article = Article.find(params[:article_id])
    @comment = @article.comments.new(comment_params)
    @comment.save ? comment_created : (render :new)
  end

  private
  
  def comment_params
    params[:comment].permit(:email, :body)
  end

  def comment_created
    flash[:notice] = "Comment has been successfully created."
    redirect_to root_path
  end
end

app/controllers/landing_controller.rb
class LandingController < ApplicationController
  def index
    @articles = Article.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/articles/new.html.erb
<% if @article.errors.any? %>
  <ul>
    <% @article.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
    <% end %>
  </ul>
<% end %>

<%= form_for @article do |f|%>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <%= f.label :content%>
  <%= f.text_area :content%>
  <%= f.submit %>
<% end %>

app/views/comments/new.html.erb
<% if @comment.errors.any? %>
  <ul>
    <% @comment.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
    <% end %>
  </ul>
<% end %>

<%= form_for [@article, @comment] do |f| %>
  <%= f.label :body %>
  <%= f.text_area :body %>
  <%= f.label :email %>
  <%= f.text_field :email %>
  <%= f.submit %>
<% end %>

app/views/landing/index.html.erb
<h1>A breaking news item</h1>
<p>Some really breaking action</p>
<%= link_to 'new article', new_article_path %>

  <% @articles.each do |article| %>
    <div id="article-<%= article.id %>">
      <ul>
        <li>
          <%= article.title %><br />
          <%= article.content %><br />
          <%= "Written by #{article.author} at #{Date.strptime("#{Date.today}", '%Y-%m-%d')}" %>
        </li>
      </ul>
      <h3> Comments </h3>
      <% unless article.comments.empty? %>
        <% article.comments.each do |comment| %>
        <% if comment.email? %>
          <h4>By: <%= comment.email %> </h4>
        <% end %>
        <p>
          <%= comment.body %>
        </p>
        <% end %>
      <% end %>
      <%= link_to 'Add Comment', new_article_comment_path(article) %>
    </div>
  <% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsArticles</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if flash[:notice] %>
      <%= flash[:notice] %>
    <% end %>

    <%= yield %>
  </body>
</html>